//
// Created by Виктория Губанова on 17.08.2020.
//

#ifndef CURRENTLINES_CURRENTLINEGENERATOR_HPP
#define CURRENTLINES_CURRENTLINEGENERATOR_HPP


class CurrentLineGenerator {

};


#endif //CURRENTLINES_CURRENTLINEGENERATOR_HPP
